### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by TangentFoxy** [TangentFoxy/GreyList#1]
- [ ] no way to create account, log in, log out, modify account
- [ ] index page not written (for logged out or logged in)
- [ ] empty password for database is still untested across domains
- [ ] need to figure out how to properly limit permissions in docker
- [ ] no editing of items
- [ ] no pagination
- [ ] done items are shown (should be hidden by default)
- [ ] no deletion of items
- [ ] no deletion of accounts (note: want delayed deletion by default!!)
- [ ] bootstrap included but unused currently
- [ ] toggling done/undone status of items does not change the link to change their status :/
- [ ] no way to add new items :(
